# Generated by Django 6.1 on 2026-09-08 01:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flota', '0001_initial'),
        ('rutas', '0001_initial'),
        ('viajes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('estado', models.CharField(choices=[('PENDIENTE_PAGO', 'Pendiente de pago'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE_PAGO', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas_como_destino', to='rutas.rutaparada')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas_como_origen', to='rutas.rutaparada')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to=settings.AUTH_USER_MODEL)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='viajes.viaje')),
            ],
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(choices=[('RUT', 'RUT'), ('PASAPORTE', 'Pasaporte'), ('OTRO', 'Otro')], max_length=10)),
                ('documento', models.CharField(max_length=30)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasajeros', to='ventas.reserva')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='ventas.reserva')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_reserva', to='flota.asiento')),
                ('pasajero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='ventas.pasajero')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.reserva')),
            ],
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='ventas_reserva_total_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gte', 0)), name='ventas_pago_monto_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='detallereserva',
            constraint=models.UniqueConstraint(fields=('reserva', 'asiento'), name='ventas_detalle_reserva_asiento_unico'),
        ),
        migrations.AddConstraint(
            model_name='detallereserva',
            constraint=models.CheckConstraint(condition=models.Q(('precio_unitario__gte', 0)), name='ventas_detalle_precio_no_negativo'),
        ),
    ]
