# Generated by Django 6.1 on 2026-09-08 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RutaParada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField()),
                ('minutos_desde_origen', models.PositiveIntegerField()),
                ('parada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas_parada', to='rutas.parada')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas_ruta', to='rutas.ruta')),
            ],
            options={
                'ordering': ('ruta', 'orden'),
            },
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activa', models.BooleanField(default=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarifas_como_destino', to='rutas.rutaparada')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarifas_como_origen', to='rutas.rutaparada')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='rutas.ruta')),
            ],
        ),
        migrations.AddConstraint(
            model_name='rutaparada',
            constraint=models.UniqueConstraint(fields=('ruta', 'orden'), name='rutas_rutaparada_ruta_orden_unico'),
        ),
        migrations.AddConstraint(
            model_name='rutaparada',
            constraint=models.UniqueConstraint(fields=('ruta', 'parada'), name='rutas_rutaparada_ruta_parada_unica'),
        ),
        migrations.AddConstraint(
            model_name='tarifa',
            constraint=models.UniqueConstraint(fields=('ruta', 'origen', 'destino'), name='rutas_tarifa_tramo_unico'),
        ),
        migrations.AddConstraint(
            model_name='tarifa',
            constraint=models.CheckConstraint(condition=models.Q(('precio__gt', 0)), name='rutas_tarifa_precio_mayor_cero'),
        ),
    ]
