# Generated by Django 6.1 on 2026-09-08 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('numero_interno', models.CharField(max_length=20, unique=True)),
                ('marca', models.CharField(blank=True, max_length=50)),
                ('modelo', models.CharField(blank=True, max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'buses',
            },
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('fila', models.PositiveSmallIntegerField()),
                ('columna', models.PositiveSmallIntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='flota.bus')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('bus', 'numero'), name='flota_asiento_bus_numero_unico'), models.UniqueConstraint(fields=('bus', 'fila', 'columna'), name='flota_asiento_bus_posicion_unica'), models.CheckConstraint(condition=models.Q(('fila__gt', 0)), name='flota_asiento_fila_mayor_cero'), models.CheckConstraint(condition=models.Q(('columna__gt', 0)), name='flota_asiento_columna_mayor_cero')],
            },
        ),
    ]
